In [100]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

import os
os.chdir('/Users/emanu/Documents/EBAC')

In [101]:
data = pd.read_csv('kc_house_data.csv')
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [102]:
data['Intercepto'] = 1
data = data[['Intercepto', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15']]
print(data.shape)
data.head()

(21613, 20)

,Intercepto,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,1,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,1,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [103]:
Xdata = data[['Intercepto', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15']].values
Ydata = data[['price']].values

In [104]:
# Dividir en bases de entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Xdata, Ydata, test_size=0.3, random_state=1)

In [105]:
X = X_train
Y = Y_train

In [106]:
# Opcion de formateo numerico 
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [107]:
XT_X = np.matmul(np.matrix.transpose(X), X)
XT_X

array([[15129.000000, 50963.000000, 32017.000000, 31442387.000000,
        230231424.000000, 22665.000000, 116.000000, 3505.000000,
        51592.000000, 115894.000000, 27017390.000000, 4424997.000000,
        29820815.000000, 1271248.000000, 1483820520.000000,
        719521.906700, -1848966.397000, 30017402.000000,
        193331191.000000],
       [50963.000000, 184941.000000, 113274.250000, 113202849.000000,
        792701993.000000, 77591.000000, 372.000000, 12596.000000,
        174087.000000, 396101.000000, 96448909.000000, 16753940.000000,
        100513486.000000, 4378090.000000, 4998226160.000000,
        2423751.361100, -6228097.770000, 104817301.000000,
        662133752.000000],
       [32017.000000, 113274.250000, 76568.375000, 74367338.750000,
        529228587.750000, 51082.750000, 306.000000, 9001.500000,
        108207.500000, 254161.750000, 63571004.750000, 10796334.000000,
        63280042.500000, 2920942.750000, 3140032296.250000,
        1522745.525575, -3912539.223500, 67932199.250000,
        438003499.000000],
       [31442387.000000, 113202849.000000, 74367338.750000,
        77688746971.000000, 575423643809.000000, 49691571.000000,
        358581.000000, 10127227.000000, 106683065.000000,
        253007293.000000, 65907346719.000000, 11781400252.000000,
        62104027960.000000, 2916435652.000000, 3083654586735.000000,
        1495470821.007197, -3842211452.765000, 69386164211.000000,
        471674253298.000000],
       [230231424.000000, 792701993.000000, 529228587.750000,
        575423643809.000000, 31855025051772.000000, 342386937.500000,
        2984896.000000, 85867012.000000, 782119892.000000,
        1844554097.000000, 504548499871.000000, 70875143938.000000,
        454836234300.000000, 19554277260.000000, 22576202731173.000000,
        10941874045.619471, -28117074084.645931, 515803572676.000000,
        15886474400668.000000],
       [22665.000000, 77591.000000, 51082.750000, 49691571.000000,
        342386937.500000, 38385.500000, 192.000000, 5408.000000,
        75865.500000, 177979.000000, 43977700.500000, 5713870.500000,
        44793918.000000, 1915175.000000, 2222910156.500000,
        1077980.398350, -2769822.711500, 46497583.000000,
        287827704.000000],
       [116.000000, 372.000000, 306.000000, 358581.000000,
        2984896.000000, 192.000000, 116.000000, 435.000000, 414.000000,
        1012.000000, 280695.000000, 77886.000000, 227698.000000,
        57654.000000, 11379088.000000, 5514.504500, -14184.577000,
        303046.000000, 2495640.000000],
       [3505.000000, 12596.000000, 9001.500000, 10127227.000000,
        85867012.000000, 5408.000000, 435.000000, 9619.000000,
        12259.000000, 30150.000000, 7734045.000000, 2393182.000000,
        6892066.000000, 745587.000000, 343816713.000000, 166699.339800,
        -428485.603000, 9052063.000000, 67325022.000000],
       [51592.000000, 174087.000000, 108207.500000, 106683065.000000,
        782119892.000000, 75865.500000, 414.000000, 12259.000000,
        182362.000000, 393523.000000, 90810383.000000, 15872682.000000,
        101587211.000000, 4097279.000000, 5060037327.000000,
        2453642.244400, -6305384.370000, 101715493.000000,
        658068204.000000],
       [115894.000000, 396101.000000, 254161.750000, 253007293.000000,
        1844554097.000000, 177979.000000, 1012.000000, 30150.000000,
        393523.000000, 908426.000000, 217850466.000000, 35156827.000000,
        228670473.000000, 9789873.000000, 11366466675.000000,
        5512099.026700, -14163296.132000, 238483847.000000,
        1538933008.000000],
       [27017390.000000, 96448909.000000, 63571004.750000,
        65907346719.000000, 504548499871.000000, 43977700.500000,
        280695.000000, 7734045.000000, 90810383.000000, 217850466.000000,
        58353858862.000000, 7553487857.000000, 53409074582.000000,
        2360607420.000000, 2649633805916.000000, 1284920913.566001,
        -3301280137.340990, 59743833908.000000, 411415656695.000000],
       [4424997.000000, 16753940.000000, 10796334.000000,
        11781400252.000000, 70875143938.000000, 5713870.500000,
        77886.000000, 2393182.000000, 15872682.000000, 35156827.000000,
        7553487857.000000, 4227912395.000000, 8694953378.000000,
        555828232.000000, 434020780819.000000, 210549907.441200,
        -540931315.424001, 9642330303.000000, 60258596603.000000],
       [29820815.000000, 100513486.000000, 63280042.500000,
        62104027960.000000, 454836234300.000000, 44793918.000000,
        227698.000000, 6892066.000000, 101587211.000000,
        228670473.000000, 53409074582.000000, 8694953378.000000,
        58792983581.000000, 2464909479.000000, 2924754608453.000000,
        1418242702.683602, -3644477075.729996, 59265919557.000000,
        381995064275.000000],
       [1271248.000000, 4378090.000000, 2920942.750000,
        2916435652.000000, 19554277260.000000, 1915175.000000,
        57654.000000, 745587.000000, 4097279.000000, 9789873.000000,
        2360607420.000000, 555828232.000000, 2464909479.000000,
        2537159496.000000, 124702091481.000000, 60490466.340600,
        -155420149.858000, 2510786006.000000, 16855694660.000000],
       [1483820520.000000, 4998226160.000000, 3140032296.250000,
        3083654586735.000000, 22576202731173.000000, 2222910156.500000,
        11379088.000000, 343816713.000000, 5060037327.000000,
        11366466675.000000, 2649633805916.000000, 434020780819.000000,
        2924754608453.000000, 124702091481.000000,
        145530041069914.000000, 70569226501.652466, -181342802207.124725,
        2943889629452.000000, 18958262520245.000000],
       [719521.906700, 2423751.361100, 1522745.525575, 1495470821.007197,
        10941874045.619471, 1077980.398350, 5514.504500, 166699.339800,
        2453642.244400, 5512099.026700, 1284920913.566001,
        210549907.441200, 1418242702.683602, 60490466.340600,
        70569226501.652466, 34220119.255041, -87935253.484719,
        1427676610.325601, 9189663182.930923],
       [-1848966.397000, -6228097.770000, -3912539.223500,
        -3842211452.765000, -28117074084.645931, -2769822.711500,
        -14184.577000, -428485.603000, -6305384.370000, -14163296.132000,
        -3301280137.340990, -540931315.424001, -3644477075.729996,
        -155420149.858000, -181342802207.124725, -87935253.484719,
        225968752.887601, -3668034704.123999, -23612605206.399075],
       [30017402.000000, 104817301.000000, 67932199.250000,
        69386164211.000000, 515803572676.000000, 46497583.000000,
        303046.000000, 9052063.000000, 101715493.000000,
        238483847.000000, 59743833908.000000, 9642330303.000000,
        59265919557.000000, 2510786006.000000, 2943889629452.000000,
        1427676610.325601, -3668034704.123999, 66539877930.000000,
        434619369449.000000],
       [193331191.000000, 662133752.000000, 438003499.000000,
        471674253298.000000, 15886474400668.000000, 287827704.000000,
        2495640.000000, 67325022.000000, 658068204.000000,
        1538933008.000000, 411415656695.000000, 60258596603.000000,
        381995064275.000000, 16855694660.000000, 18958262520245.000000,
        9189663182.930923, -23612605206.399075, 434619369449.000000,
        14167742946397.000000]])

In [108]:
XT_X_inv =np.linalg.inv(XT_X)
XT_X_inv

array([[303.728801, -0.011528, 0.001412, 0.674431, -0.000000, 0.067044,
        -0.019625, 0.024004, -0.037159, 0.019175, -0.674453, -0.674386,
        -0.002651, -0.000028, -0.002872, 0.033335, 0.149774, -0.000064,
        -0.000000],
       [-0.011528, 0.000123, -0.000040, 0.000057, 0.000000, 0.000008,
        0.000060, 0.000009, -0.000006, 0.000020, -0.000057, -0.000058,
        0.000000, 0.000000, 0.000000, 0.000017, 0.000007, 0.000000,
        0.000000],
       [0.001412, -0.000040, 0.000374, 0.000075, -0.000000, -0.000110,
        0.000012, -0.000004, -0.000016, -0.000020, -0.000075, -0.000075,
        -0.000003, -0.000000, 0.000000, -0.000030, 0.000031, 0.000000,
        0.000000],
       [0.573441, 0.000061, 0.000066, 419430.508352, -0.000000, 0.000408,
        0.000685, 0.000301, 0.000072, 0.000370, -419430.508353,
        -419430.508352, -0.000023, -0.000000, 0.000021, 0.005959,
        0.023879, -0.000001, -0.000000],
       [-0.000000, 0.000000, -0.000000, -0.000000, 0.000000, 0.000000,
        0.000000, -0.000000, 0.000000, -0.000000, 0.000000, 0.000000,
        0.000000, 0.000000, 0.000000, 0.000000, -0.000000, 0.000000,
        -0.000000],
       [0.067044, 0.000008, -0.000110, 0.000449, 0.000000, 0.000459,
        -0.000016, -0.000005, 0.000015, -0.000024, -0.000449, -0.000449,
        -0.000002, -0.000000, -0.000000, -0.000104, 0.000154, 0.000000,
        0.000000],
       [-0.019625, 0.000060, 0.000012, 0.000700, 0.000000, -0.000016,
        0.010506, -0.000496, -0.000029, 0.000036, -0.000699, -0.000699,
        -0.000001, -0.000000, 0.000000, 0.000022, 0.000161, 0.000000,
        -0.000000],
       [0.024004, 0.000009, -0.000004, 0.000310, -0.000000, -0.000005,
        -0.000496, 0.000162, -0.000001, -0.000014, -0.000310, -0.000310,
        0.000000, -0.000000, -0.000000, 0.000077, 0.000043, -0.000000,
        -0.000000],
       [-0.037159, -0.000006, -0.000016, 0.000057, 0.000000, 0.000015,
        -0.000029, -0.000001, 0.000195, -0.000005, -0.000057, -0.000057,
        0.000002, 0.000000, 0.000000, 0.000051, -0.000008, 0.000000,
        -0.000000],
       [0.019175, 0.000020, -0.000020, 0.000397, -0.000000, -0.000024,
        0.000036, -0.000014, -0.000005, 0.000165, -0.000397, -0.000397,
        -0.000001, -0.000000, 0.000000, -0.000132, 0.000153, -0.000000,
        0.000000],
       [-0.573462, -0.000061, -0.000066, -419430.508353, 0.000000,
        -0.000408, -0.000685, -0.000301, -0.000072, -0.000370,
        419430.508353, 419430.508352, 0.000023, 0.000000, -0.000021,
        -0.005959, -0.023879, 0.000001, 0.000000],
       [-0.573397, -0.000061, -0.000066, -419430.508351, 0.000000,
        -0.000407, -0.000685, -0.000301, -0.000072, -0.000370,
        419430.508352, 419430.508351, 0.000023, 0.000000, -0.000021,
        -0.005959, -0.023879, 0.000001, 0.000000],
       [-0.002651, 0.000000, -0.000003, -0.000025, 0.000000, -0.000002,
        -0.000001, 0.000000, 0.000002, -0.000001, 0.000025, 0.000025,
        0.000000, 0.000000, 0.000000, 0.000005, -0.000008, 0.000000,
        -0.000000],
       [-0.000028, 0.000000, -0.000000, -0.000000, 0.000000, -0.000000,
        -0.000000, -0.000000, 0.000000, -0.000000, 0.000000, 0.000000,
        0.000000, 0.000000, 0.000000, 0.000000, -0.000000, 0.000000,
        -0.000000],
       [-0.002872, 0.000000, 0.000000, 0.000022, 0.000000, -0.000000,
        0.000000, -0.000000, 0.000000, 0.000000, -0.000022, -0.000022,
        0.000000, 0.000000, 0.000000, -0.000003, 0.000006, 0.000000,
        -0.000000],
       [0.033335, 0.000017, -0.000030, 0.005824, 0.000000, -0.000104,
        0.000022, 0.000077, 0.000051, -0.000132, -0.005824, -0.005824,
        0.000005, 0.000000, -0.000003, 0.004047, -0.000306, -0.000000,
        0.000000],
       [0.149774, 0.000007, 0.000031, 0.024663, -0.000000, 0.000154,
        0.000161, 0.000043, -0.000008, 0.000153, -0.024663, -0.024662,
        -0.000008, -0.000000, 0.000006, -0.000306, 0.006144, -0.000000,
        -0.000000],
       [-0.000064, 0.000000, 0.000000, -0.000001, 0.000000, 0.000000,
        0.000000, -0.000000, 0.000000, -0.000000, 0.000001, 0.000001,
        0.000000, 0.000000, 0.000000, -0.000000, -0.000000, 0.000000,
        -0.000000],
       [-0.000000, 0.000000, 0.000000, -0.000000, -0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, 0.000000, -0.000000, -0.000000,
        0.000000]])

In [109]:
XT_Y = np.matmul(np.matrix.transpose(X), Y)
XT_Y

array([[8134792844.000000],
       [28921660282.000000],
       [19344041227.500000],
       [20285899254544.000000],
       [142407378785985.000000],
       [12932928855.500000],
       [186574092.000000],
       [3471948304.000000],
       [27861195467.000000],
       [66500354540.000000],
       [17161125245981.000000],
       [3124774008563.000000],
       [16042657850839.000000],
       [956236284337.000000],
       [797829485755029.000000],
       [387121579186.852905],
       [-994165337864.433350],
       [18255655339721.000000],
       [115936311020042.000000]])

In [110]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[-15549926.683594],
       [-3897650.445815],
       [7468283.853207],
       [281600.000000],
       [1.584783],
       [5996001.208200],
       [9005531.198687],
       [-783684.880600],
       [695537.037980],
       [1133530.494625],
       [-283648.000000],
       [-277504.000000],
       [-2544.069913],
       [21.838811],
       [-552.934686],
       [613987.026688],
       [-205578.424078],
       [19.256424],
       [-0.311620]])

In [111]:
Y_pred = np.matmul(X_test, betas)
Y_pred

array([[2948297.189213],
       [-568849.504575],
       [4728015.854360],
       ...,
       [-5668493.059026],
       [24231592.418741],
       [-7157467.625741]])

In [113]:
# Calculo de residuales
Resid  = Y_test - Y_pred
Resid

array([[-2489297.189213],
       [1013849.504575],
       [-3671015.854360],
       ...,
       [5898493.059026],
       [-22551592.418741],
       [7450467.625741]])

In [118]:
# Calculo del TSS (Suma Total de Cuadrados)
TSS = np.matmul(np.matrix.transpose(Y), Y) - len(Y)*(Y.mean()**2)
TSS

array([[1900668073054776.000000]])

In [119]:
# Calculo del ESS (Suma Explicada de Cuadrados)
ESS = sum((Y - Y.mean())**2)
ESS

array([1900668073054772.750000])

In [120]:
# Calculo de RSS (Residuales al Cuadrado)
RSS = TSS - ESS
RSS

array([[3.250000]])

In [121]:
# Calculo del Coeficioente de Determinacion R Cuadrada
RSq = 1 - RSS / TSS
RSq

array([[1.000000]])

In [122]:
# Calculo del Coeficiente de Determinacion R Cuadrada Ajustada)
RSqA = 1 - (RSS / (X.shape[0] - X.shape[1])) / (TSS / (X.shape[0] -1))
RSqA

array([[1.000000]])

In [123]:
# Calculo de la varianza del error de regresion
s_cuad = RSS / (len(Y) - X.shape[1])
s_cuad

array([[0.000215]])

In [124]:
# Desviacion estandar del error de regresion
import math 
s = math.sqrt(s_cuad)
s

0.014665924614723923

In [125]:
# Calculo de las t's estadisticas para cada coeficiente de regresion 
result_t = []
for i in range(0, X.shape[1]):
    t = float(betas[i] / (s*math.sqrt(XT_X_inv[i][i])))
    result_t.append(t)
result_t

[-60838137.41869363,
 -23984122403.36847,
 26332357036.55944,
 29647.84925143265,
 401960644.2163485,
 19087059843.030987,
 5990763215.921901,
 -4202282307.3537025,
 3393282717.311276,
 6024994278.045365,
 -29863.469973221712,
 -29216.607807813703,
 -402124706.0736652,
 68375203.99643344,
 -192359597.23817074,
 658091588.465363,
 -178827604.15412036,
 63692815.08605842,
 -50202910.9049036]

# Criterio 1:

In [126]:
# Obtener valor critico de la t de Student de tablas
import scipy.stats 

grados_libertad = len(Y) - X.shape[1]
# la t critica se obtendra a un nivel de confianza del 95% (Alfa = 5%)
t_critico = abs(scipy.stats.t.ppf(q=0.025, df=grados_libertad))
t_critico

np.float64(1.9601209969846756)

In [127]:
for i in range(0, X.shape[1]):
    if (abs(result_t[i]) > t_critico):
        print('Beta', i, 'es significativa') # Aqui se rechaza la hipotesis nula
    else: 
         print('Beta', i, ' NO es significativa') # Aqui NO se rechaza la H0

Beta 0 es significativa
Beta 1 es significativa
Beta 2 es significativa
Beta 3 es significativa
Beta 4 es significativa
Beta 5 es significativa
Beta 6 es significativa
Beta 7 es significativa
Beta 8 es significativa
Beta 9 es significativa
Beta 10 es significativa
Beta 11 es significativa
Beta 12 es significativa
Beta 13 es significativa
Beta 14 es significativa
Beta 15 es significativa
Beta 16 es significativa
Beta 17 es significativa
Beta 18 es significativa

# Criterio 2:

In [128]:
# Calculo de valores p
for i in range(0, X.shape[1]):
    print('Valor p de Beta', i, ':', scipy.stats.t.sf(abs(result_t[i]), df=grados_libertad)*2)

Valor p de Beta 0 : 0.0
Valor p de Beta 1 : 0.0
Valor p de Beta 2 : 0.0
Valor p de Beta 3 : 0.0
Valor p de Beta 4 : 0.0
Valor p de Beta 5 : 0.0
Valor p de Beta 6 : 0.0
Valor p de Beta 7 : 0.0
Valor p de Beta 8 : 0.0
Valor p de Beta 9 : 0.0
Valor p de Beta 10 : 0.0
Valor p de Beta 11 : 0.0
Valor p de Beta 12 : 0.0
Valor p de Beta 13 : 0.0
Valor p de Beta 14 : 0.0
Valor p de Beta 15 : 0.0
Valor p de Beta 16 : 0.0
Valor p de Beta 17 : 0.0
Valor p de Beta 18 : 0.0

# Criterio 3:

In [129]:
# Calculo de intervalos de confianza del 95% para el verdadero valor del coeficiente de cada Beta
for i in range(0, X.shape[1]):
    print('El valor de Beta', i, 'se encuentra entre', float(betas[i]) - t_critico*s*math.sqrt(XT_X_inv[i][i]), 
          'y', float(betas[i]) + t_critico*s*math.sqrt(XT_X_inv[i][i]))

El valor de Beta 0 se encuentra entre -15549927.184590971 y -15549926.182596529
El valor de Beta 1 se encuentra entre -3897650.446133744 y -3897650.445496667
El valor de Beta 2 se encuentra entre 7468283.852650712 y 7468283.853762557
El valor de Beta 3 se encuentra entre 281581.38245819893 y 281618.61754180107
El valor de Beta 4 se encuentra entre 1.5847834296864056 y 1.5847834451424825
El valor de Beta 5 se encuentra entre 5996001.20758375 y 5996001.208815252
El valor de Beta 6 se encuentra entre 9005531.195740076 y 9005531.201633124
El valor de Beta 7 se encuentra entre -783684.8809655191 y -783684.880234432
El valor de Beta 8 se encuentra entre 695537.037578543 y 695537.0383820932
El valor de Beta 9 se encuentra entre 1133530.4942563183 y 1133530.4949938648
El valor de Beta 10 se encuentra entre -283666.6175418011 y -283629.3824581989
El valor de Beta 11 se encuentra entre -277522.61754180107 y -277485.38245819893
El valor de Beta 12 se encuentra entre -2544.069925311303 y -2544.06990050962
El valor de Beta 13 se encuentra entre 21.83881050048154 y 21.838811752593703
El valor de Beta 14 se encuentra entre -552.9346914606391 y -552.934680191964
El valor de Beta 15 se encuentra entre 613987.0248588662 y 613987.0285163779
El valor de Beta 16 se encuentra entre -205578.4263316021 y -205578.4218249311
El valor de Beta 17 se encuentra entre 19.256423508990963 y 19.25642469420852
El valor de Beta 18 se encuentra entre -0.3116195847951076 y -0.31161956046137645

In [130]:
# Comparacion de resultados contra reporte automatizado
import statsmodels.api as sm 

regressor = sm.OLS(Y, X).fit()
print(regressor.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.704
Model:                            OLS   Adj. R-squared:                  0.704
Method:                 Least Squares   F-statistic:                     2113.
Date:                Tue, 10 Mar 2026   Prob (F-statistic):               0.00
Time:                        16:52:09   Log-Likelihood:            -2.0558e+05
No. Observations:               15129   AIC:                         4.112e+05
Df Residuals:                   15111   BIC:                         4.113e+05
Df Model:                          17
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.241e+06   3.36e+06      1.261      0.207   -2.35e+06    1.08e+07
x1         -3.238e+04   2138.358    -15.140      0.000   -3.66e+04   -2.82e+04
x2          3.758e+04   3731.920     10.070      0.000    3.03e+04    4.49e+04
x3           106.6075      2.631     40.524      0.000     101.451     111.764
x4             0.0926      0.052      1.786      0.074      -0.009       0.194
x5          9713.5747   4133.557      2.350      0.019    1611.303    1.78e+04
x6          5.633e+05   1.98e+04     28.479      0.000    5.25e+05    6.02e+05
x7          5.166e+04   2453.904     21.054      0.000    4.69e+04    5.65e+04
x8          2.673e+04   2697.128      9.910      0.000    2.14e+04     3.2e+04
x9          9.525e+04   2475.585     38.476      0.000    9.04e+04       1e+05
x10           69.7277      2.612     26.698      0.000      64.608      74.847
x11           36.8806      3.055     12.073      0.000      30.893      42.868
x12        -2544.0699     83.247    -30.560      0.000   -2707.244   -2380.895
x13           21.8388      4.203      5.196      0.000      13.601      30.077
x14         -552.9347     37.823    -14.619      0.000    -627.073    -478.796
x15          6.14e+05   1.23e+04     50.013      0.000     5.9e+05    6.38e+05
x16        -2.056e+05   1.51e+04    -13.590      0.000   -2.35e+05   -1.76e+05
x17           19.2564      3.978      4.840      0.000      11.459      27.054
x18           -0.3116      0.082     -3.815      0.000      -0.472      -0.152
==============================================================================
Omnibus:                    10777.741   Durbin-Watson:                   2.031
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           506687.708
Skew:                           2.899   Prob(JB):                         0.00
Kurtosis:                      30.752   Cond. No.                     3.16e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.53e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [131]:
data = pd.DataFrame(X)
data2 = data.iloc[:,1:3]
data2.corr()

          1         2
1  1.000000  0.501515
2  0.501515  1.000000